source "https://rubygems.org"

gem 'rspec'
gem 'rspec_junit_formatter'
gem 'pupperware',
    :git => 'https://github.com/puppetlabs/pupperware.git',
    :branch => 'fix-stderr-support',
    :glob => 'gem/*.gemspec'
