source ENV['GEM_SOURCE'] || 'https://artifactory.delivery.puppetlabs.net/artifactory/api/gems/rubygems/'

gem 'beaker', '~> 2.7'
gem 'beaker-abs', '~> 0.2'
gem 'rototiller', '= 0.1.0'
gem 'beaker-hostgenerator', '~> 0.7.0'
