source ENV['GEM_SOURCE'] || 'http://rubygems.delivery.puppetlabs.net'

gem 'beaker', '~> 3.0'
gem 'beaker-pe'
gem 'beaker-answers'
gem 'beaker-abs', '~> 0.2'
gem 'rototiller', '= 0.1.0'
gem 'beaker-hostgenerator', '~> 0.7.0'
gem 'beaker-qa-i18n'
